Develop
kanzucodefoundation/project-zoe-client pull request #117
Opened 2022-08-22 09:47 UTC by AtwijukireBrendah

# Ticket No
- Ticket number here

# Summary of changes
- Summary of changes here

# How should this be tested? [Screenshots, Video or Type instructions]
- How should this be tested here

# Notes for reviewers
- Notes for reviewers here

# Out of scope
-  Out of scope here

2022-08-24 09:15 UTC, jacksono requested changes
Some few things to work on before we can move forward with this.

2022-08-24 09:15 UTC, jacksono commented on src/modules/dashboard/DashboardFilter.tsx
> +//   console.log(profile);
Remove this console log statement.

2022-08-24 09:15 UTC, jacksono commented on src/modules/dashboard/DashboardFilter.tsx
> +					filter={{ churchName: profile.aud}}
This seems to be over indented.

2022-11-12 13:52 UTC, kakoma commented
Combined into [this single PR](https://github.com/kanzucodefoundation/project-zoe-client/pull/119)

2022-11-12 13:52 UTC, closed without merging